### PR TITLE
Fix $.browser undefined variable comparison.

### PR DESCRIPTION
**Pull request by rteijeiro**
This fix is related to an error found in one Drupal module:

http://drupal.org/node/1969724

Hope the fix is correct. Thanks for your time :)

### CODE REVIEW

**Comment by rteijeiro** [comment]
Hi @eduardolundgren. It's closed but no merged. Could you tell me if there is any problem, please?

**Comment by eduardolundgren** [comment]
No it's fine, it was accidentally closed. It's on our queue.

**Comment by eduardolundgren** [comment]
Merged. Thx.

**Comment by rteijeiro** [comment]
Great!! Thanks :+1:

**Pull request closed without merging**
